In [ ]:
#mount the data using this drive link :https://drive.google.com/drive/folders/14y64y6SWmA7_6I19ildMfwCveG8G9Prb

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import drive

In [ ]:
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
netflix_dataset=pd.read_csv("/content/drive/My Drive/Netflix_Rec/Copy of combined_data_1.txt.zip",names=['cust_id','Rating'],usecols=[0,1])

In [ ]:
netflix_dataset

          cust_id  Rating
0              1:     NaN
1         1488844     3.0
2          822109     5.0
3          885013     4.0
4           30878     4.0
...           ...     ...
24058258  2591364     2.0
24058259  1791000     2.0
24058260   512536     5.0
24058261   988963     3.0
24058262  1704416     3.0

[24058263 rows x 2 columns]

In [ ]:
#in this cust_id we have both movie_id and customer_id
#for movie_id in rating columns it will contain nan

In [ ]:
#data cleaning
netflix_dataset.isnull()["Rating"].sum()

4499

In [ ]:
Movie_id=netflix_dataset.isnull()["Rating"].sum()
Movie_id

4499

In [ ]:
#create seperate column for movie_id in dataset because in your dataset contain both cust_id and movie_id i same column
movie_id=None
movie_np=[]

for i in netflix_dataset['cust_id']:
  if ":" in i:
    movie_id=int(i.replace(":",""))

  movie_np.append(movie_id)

In [ ]:
movie_np

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 ...]

In [ ]:
netflix_dataset['movie_id']=movie_np

In [ ]:
netflix_dataset

          cust_id  Rating  movie_id
0              1:     NaN         1
1         1488844     3.0         1
2          822109     5.0         1
3          885013     4.0         1
4           30878     4.0         1
...           ...     ...       ...
24058258  2591364     2.0      4499
24058259  1791000     2.0      4499
24058260   512536     5.0      4499
24058261   988963     3.0      4499
24058262  1704416     3.0      4499

[24058263 rows x 3 columns]

In [ ]:
#cleaning the dataset
#keep only rating columns which has no null values
netflix_dataset=netflix_dataset[netflix_dataset['Rating'].notnull()]

In [ ]:
netflix_dataset

          cust_id  Rating  movie_id
1         1488844     3.0         1
2          822109     5.0         1
3          885013     4.0         1
4           30878     4.0         1
5          823519     3.0         1
...           ...     ...       ...
24058258  2591364     2.0      4499
24058259  1791000     2.0      4499
24058260   512536     5.0      4499
24058261   988963     3.0      4499
24058262  1704416     3.0      4499

[24053764 rows x 3 columns]

In [ ]:
netflix_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   cust_id   object
 1   Rating    float64
 2   movie_id  int64
dtypes: float64(1), int64(1), object(1)
memory usage: 734.1+ MB

In [ ]:
#change the datatype of cust_id from object to int
netflix_dataset['cust_id']=netflix_dataset['cust_id'].astype(int)

/tmp/ipykernel_18783/646214013.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  netflix_dataset['cust_id']=netflix_dataset['cust_id'].astype(int)

In [ ]:
netflix_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   cust_id   int64
 1   Rating    float64
 2   movie_id  int64
dtypes: float64(1), int64(2)
memory usage: 734.1 MB

In [ ]:
netflix_dataset

          cust_id  Rating  movie_id
1         1488844     3.0         1
2          822109     5.0         1
3          885013     4.0         1
4           30878     4.0         1
5          823519     3.0         1
...           ...     ...       ...
24058258  2591364     2.0      4499
24058259  1791000     2.0      4499
24058260   512536     5.0      4499
24058261   988963     3.0      4499
24058262  1704416     3.0      4499

[24053764 rows x 3 columns]

In [ ]:
#pre filtered the dataset:
#prefilter means in our data it will contain unreliable data and unrated data
#it means it contain less rating movie and unrated users in customer_id

In [ ]:
#count the cust_id from rating
dataset_cust_summary=netflix_dataset.groupby('cust_id')['Rating'].agg(['count'])
dataset_cust_summary

         count
cust_id
6          153
7          195
8           21
10          49
25           4
...        ...
2649404     12
2649409     10
2649421      3
2649426     74
2649429     62

[470758 rows x 1 columns]

In [ ]:
#create abenchmark for cust_id to filter the data here we will use 60%
cust_benchmark=round(dataset_cust_summary['count'].quantile(0.6),0)
cust_benchmark

36.0

In [ ]:
#60% of customer below the 36 rating and 40% of data have 36 and more

In [ ]:
drop_cust=dataset_cust_summary[dataset_cust_summary['count']<cust_benchmark].index
drop_cust

Index([      8,      25,      33,      83,      94,     126,     130,     133,
           142,     149,
       ...
       2649337, 2649343, 2649351, 2649376, 2649379, 2649384, 2649401, 2649404,
       2649409, 2649421],
      dtype='int64', name='cust_id', length=282042)

In [ ]:
len(drop_cust)

282042

In [ ]:
#282042 user is remove from dataset

In [ ]:
#similarly we will do for movies
movie_summary=netflix_dataset.groupby('movie_id')['Rating'].agg(['count'])
movie_summary

          count
movie_id
1           547
2           145
3          2012
4           142
5          1140
...         ...
4495        614
4496       9519
4497        714
4498        269
4499        428

[4499 rows x 1 columns]

In [ ]:
#create a bench mark for a movie
movie_benchmark=round(movie_summary['count'].quantile(0.6),0)
movie_benchmark

908.0

In [ ]:
#60% of movie below the 908 rating and 40% of movie above 908 and more

In [ ]:
#drop the movie below 908 rating
drop_movie=movie_summary[movie_summary['count']<movie_benchmark].index
drop_movie

Index([   1,    2,    4,    7,    9,   10,   11,   12,   13,   14,
       ...
       4480, 4481, 4486, 4487, 4491, 4494, 4495, 4497, 4498, 4499],
      dtype='int64', name='movie_id', length=2699)

In [ ]:
len(drop_movie)

2699

In [ ]:
#2699 movie to be remove from datset

In [ ]:
#now chage in dataset by using drop data
netflix_dataset=netflix_dataset[~netflix_dataset['movie_id'].isin(drop_movie)]
netflix_dataset=netflix_dataset[~netflix_dataset['cust_id'].isin(drop_cust)]

In [ ]:
netflix_dataset

          cust_id  Rating  movie_id
696        712664     5.0         3
697       1331154     4.0         3
698       2632461     3.0         3
699         44937     5.0         3
700        656399     4.0         3
...           ...     ...       ...
24056842  1055714     5.0      4496
24056843  2643029     4.0      4496
24056844   267802     4.0      4496
24056845  1559566     3.0      4496
24056846   293198     3.0      4496

[19695836 rows x 3 columns]

In [ ]:
# Final data which is left behind is having 1 crore 96 lakh 95 thousand 8 hundred thirty six rows

#model buliding

In [ ]:
#in combined dataset it will contain only cust_id,movie_id,Rating
#but in dataset it will  not contain any movie name

In [ ]:
#load the another dataset for movie genre(name)
df=pd.read_csv("/content/drive/My Drive/Netflix_Rec/Copy of movie_titles.csv",names=['movie_id','title_year','genre'],encoding="ISO-8859-1",usecols=[0,1,2])

In [ ]:
df

       movie_id  title_year                                              genre
0             1      2003.0                                    Dinosaur Planet
1             2      2004.0                         Isle of Man TT 2004 Review
2             3      1997.0                                          Character
3             4      1994.0                       Paula Abdul's Get Up & Dance
4             5      2004.0                           The Rise and Fall of ECW
...         ...         ...                                                ...
17765     17766      2002.0  Where the Wild Things Are and Other Maurice Se...
17766     17767      2004.0                  Fidel Castro: American Experience
17767     17768      2000.0                                              Epoch
17768     17769      2003.0                                        The Company
17769     17770      2003.0                                       Alien Hunter

[17770 rows x 3 columns]

In [ ]:
#instation of scikit-suprise for recommendiation

In [ ]:
!pip install scikit-surprise

Requirement already satisfied: scikit-surprise in /usr/local/lib/python3.12/dist-packages (1.1.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.5.3)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.16.3)

In [ ]:
#when scikit shows an error we need install older version of numpy
#because of numpy it will show any error

In [ ]:
pip install numpy==1.26.4

Requirement already satisfied: numpy==1.26.4 in /usr/local/lib/python3.12/dist-packages (1.26.4)

In [ ]:
from surprise import Reader,Dataset,SVD
from surprise.model_selection import cross_validate

In [ ]:
reader=Reader()

In [ ]:
#in huge amount of data we will take only 1,00,000 data because of fast runtime
data=Dataset.load_from_df(netflix_dataset[['cust_id','movie_id','Rating']][:100000],reader)

In [ ]:
data

In [ ]:
#it will convert data from pandas to surprise

In [ ]:
#train the recommediation model
model=SVD()

In [ ]:
model

In [ ]:
cross_validate(model,data,measures=['RMSE'],cv=3)

{'test_rmse': array([1.01695421, 1.01641222, 1.02238692]),
 'fit_time': (2.050485610961914, 1.531904935836792, 1.528705358505249),
 'test_time': (0.19245648384094238, 0.5038816928863525, 0.4814329147338867)}

#recommendation system

In [ ]:
netflix_dataset

          cust_id  Rating  movie_id
696        712664     5.0         3
697       1331154     4.0         3
698       2632461     3.0         3
699         44937     5.0         3
700        656399     4.0         3
...           ...     ...       ...
24056842  1055714     5.0      4496
24056843  2643029     4.0      4496
24056844   267802     4.0      4496
24056845  1559566     3.0      4496
24056846   293198     3.0      4496

[19695836 rows x 3 columns]

In [ ]:
df

       movie_id  title_year                                              genre
0             1      2003.0                                    Dinosaur Planet
1             2      2004.0                         Isle of Man TT 2004 Review
2             3      1997.0                                          Character
3             4      1994.0                       Paula Abdul's Get Up & Dance
4             5      2004.0                           The Rise and Fall of ECW
...         ...         ...                                                ...
17765     17766      2002.0  Where the Wild Things Are and Other Maurice Se...
17766     17767      2004.0                  Fidel Castro: American Experience
17767     17768      2000.0                                              Epoch
17768     17769      2003.0                                        The Company
17769     17770      2003.0                                       Alien Hunter

[17770 rows x 3 columns]

In [ ]:
#1. Find out the list of most popular and liked genre
#2. Create Model that finds the best suited Movie for one user in every genre.
#3. Find what Genre Movies have received the best and worst ratings based on User Rating.

In [ ]:
#Most Popular - Most Watched
#Most Like - Higher rating

# Most Watched + Highher Rating

In [ ]:
#1. Find out the list of most popular and liked genre

In [ ]:
most_popular=netflix_dataset.groupby('movie_id')["Rating"].agg(['count'])
most_popular

          count
movie_id
3          1699
5           869
6           849
8         11043
16         2581
...         ...
4489       1234
4490       8532
4492       8207
4493       5223
4496       8488

[1800 rows x 1 columns]

In [ ]:
#top 10 most popular genre
movie_popularity = pd.merge(most_popular, df, on='movie_id', how='inner')
popular_movies = movie_popularity.sort_values(by='count', ascending=False).head(10)
popular_movies

,movie_id,count,title_year,genre
763,1905,142993,2003.0,Pirates of the Caribbean: The Curse of the Bla...
986,2452,121278,2001.0,Lord of the Rings: The Fellowship of the Ring
236,571,120186,1999.0,American Beauty
1716,4306,119073,1999.0,The Sixth Sense
1532,3860,118609,2003.0,Bruce Almighty
1773,4432,113853,2003.0,The Italian Job
1569,3938,112016,2004.0,Shrek 2
1579,3962,111102,2003.0,Finding Nemo (Widescreen)
1131,2862,109025,1991.0,The Silence of the Lambs
1104,2782,106472,1995.0,Braveheart

In [ ]:
most_like=netflix_dataset.groupby('movie_id')["Rating"].agg(['count'])
most_like.head()

          count
movie_id
3          1699
5           869
6           849
8         11043
16         2581

In [ ]:
#top10 liked genre
top_liked_genres = genre_summary.sort_values(by='average_rating',ascending=False).head(10)
print("Top 10 Most Liked genres:")
print(top_liked_genres)

Top 10 Most Liked genres:
                                              genre  total_ratings  \
774                                  Lost: Season 1           5533
1552                         The Simpsons: Season 6           7777
435           Family Guy: Freakin' Sweet Collection           8763
669                                       Inu-Yasha           1264
1155                       Six Feet Under: Season 4           9588
1212                        Stargate SG-1: Season 8           1634
1624                        The West Wing: Season 3           5678
526                         Gilmore Girls: Season 3           4163
1299                    The Best of Friends: Vol. 4           9617
772   Lord of the Rings: The Fellowship of the Ring         121278

      average_rating
774         4.667269
1552        4.588016
435         4.520370
669         4.495253
1155        4.466834
1212        4.463280
1624        4.456323
526         4.438146
1299        4.436311
772         4.433863

In [ ]:
genre_summary

,genre,total_ratings,average_rating
0,10,4747,3.116284
1,10 Things I Hate About You,41956,3.718443
2,101 Dalmatians II: Patch's London Adventure,5974,3.537831
3,11:14,1947,3.252183
4,13 Ghosts,6902,3.606201
...,...,...,...
1782,Yu Yu Hakusho,836,4.337321
1783,Yu-Gi-Oh!: The Movie,2346,3.247656
1784,Zatoichi,756,3.742063
1785,Zeus and Roxanne,1096,3.371350
1786,Zorro,1864,3.313841

In [ ]:
#2. Create Model that finds the best suited Movie for one user in every genre.
user_rating=netflix_dataset[netflix_dataset['cust_id']==1331154]

In [ ]:
user_rating

          cust_id  Rating  movie_id
697       1331154     4.0         3
5178      1331154     4.0         8
31460     1331154     3.0        18
92840     1331154     4.0        30
224761    1331154     3.0        44
...           ...     ...       ...
23439584  1331154     4.0      4389
23546489  1331154     2.0      4402
23649431  1331154     4.0      4432
23844441  1331154     3.0      4472
23985561  1331154     4.0      4488

[253 rows x 3 columns]

In [ ]:
#user_133114 have rate 253 movie's

In [ ]:
#create a copy of user 1331154
user_1331154=df.copy()
user_1331154

       movie_id  title_year                                              genre
0             1      2003.0                                    Dinosaur Planet
1             2      2004.0                         Isle of Man TT 2004 Review
2             3      1997.0                                          Character
3             4      1994.0                       Paula Abdul's Get Up & Dance
4             5      2004.0                           The Rise and Fall of ECW
...         ...         ...                                                ...
17765     17766      2002.0  Where the Wild Things Are and Other Maurice Se...
17766     17767      2004.0                  Fidel Castro: American Experience
17767     17768      2000.0                                              Epoch
17768     17769      2003.0                                        The Company
17769     17770      2003.0                                       Alien Hunter

[17770 rows x 3 columns]

In [ ]:
#remove the movie which are less rating
user_1331154=user_1331154[~user_1331154['movie_id'].isin(drop_movie)]
user_1331154

       movie_id  title_year                                              genre
2             3      1997.0                                          Character
4             5      2004.0                           The Rise and Fall of ECW
5             6      1997.0                                               Sick
7             8      2004.0                         What the #$*! Do We Know!?
15           16      1996.0                                          Screamers
...         ...         ...                                                ...
17765     17766      2002.0  Where the Wild Things Are and Other Maurice Se...
17766     17767      2004.0                  Fidel Castro: American Experience
17767     17768      2000.0                                              Epoch
17768     17769      2003.0                                        The Company
17769     17770      2003.0                                       Alien Hunter

[15071 rows x 3 columns]

In [ ]:
user_1331154["Estimator"]=user_1331154['movie_id'].apply(lambda x:model.predict(1331154,x).est)

/tmp/ipykernel_18783/1947700176.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  user_1331154["Estimator"]=user_1331154['movie_id'].apply(lambda x:model.predict(1331154,x).est)

In [ ]:
user_1331154

,movie_id,title_year,genre,Estimator
2,3,1997.0,Character,3.966094
4,5,2004.0,The Rise and Fall of ECW,3.659063
5,6,1997.0,Sick,3.029507
7,8,2004.0,What the #$*! Do We Know!?,4.055923
15,16,1996.0,Screamers,3.380943
...,...,...,...,...
17765,17766,2002.0,Where the Wild Things Are and Other Maurice Se...,3.657494
17766,17767,2004.0,Fidel Castro: American Experience,3.657494
17767,17768,2000.0,Epoch,3.657494
17768,17769,2003.0,The Company,3.657494
17769,17770,2003.0,Alien Hunter,3.657494

In [ ]:
user_1331154.sort_values('Estimator',ascending=False)

    movie_id  title_year                       genre  Estimator
7          8      2004.0  What the #$*! Do We Know!?   4.055923
17        18      1994.0            Immortal Beloved   4.017294
29        30      2003.0      Something's Gotta Give   4.014276
2          3      1997.0                   Character   3.966094
27        28      2002.0             Lilo and Stitch   3.886830
..       ...         ...                         ...        ...
15        16      1996.0                   Screamers   3.380943
23        24      1981.0         My Bloody Valentine   3.344834
25        26      2004.0             Never Die Alone   3.216993
16        17      2005.0                   7 Seconds   3.198502
5          6      1997.0                        Sick   3.029507

[15071 rows x 4 columns]

In [ ]:
#the best suited Movie for one user in every genre are above

In [ ]:
#3. Find what Genre Movies have received the best and worst ratings based on User Rating.

In [ ]:
best_rated_genres_movie= genre_summary.sort_values(by='average_rating', ascending=False).head(10)
print("Top 10 Best Rated Genres:")
print(best_rated_genres_movie)

worst_rated_genres_movies = genre_summary.sort_values(by='average_rating', ascending=True).head(10)
print("\nTop 10 Worst Rated Genres:")
print(worst_rated_genres_movies)

Top 10 Best Rated Genres:
                                              genre  total_ratings  \
774                                  Lost: Season 1           5533
1552                         The Simpsons: Season 6           7777
435           Family Guy: Freakin' Sweet Collection           8763
669                                       Inu-Yasha           1264
1155                       Six Feet Under: Season 4           9588
1212                        Stargate SG-1: Season 8           1634
1624                        The West Wing: Season 3           5678
526                         Gilmore Girls: Season 3           4163
1299                    The Best of Friends: Vol. 4           9617
772   Lord of the Rings: The Fellowship of the Ring         121278

      average_rating
774         4.667269
1552        4.588016
435         4.520370
669         4.495253
1155        4.466834
1212        4.463280
1624        4.456323
526         4.438146
1299        4.436311
772         4.433863

Top 10 Worst Rated Genres:
                                            genre  total_ratings  \
1125                            Shanghai Surprise           1168
618                             House of the Dead           4947
384                                        Druids           1185
1184                                  Spice World           1917
512                                         Gerry           3381
726                                     Last Days           1227
408                           Ernest Goes to Jail           3216
481                           Freddy Got Fingered           4491
375                             Dr. T & the Women           5630
1215  Starship Troopers 2: Hero of the Federation           4193

      average_rating
1125        1.755993
618         1.962401
384         2.012658
1184        2.122587
512         2.192842
726         2.224939
408         2.229789
481         2.230461
375         2.254707
1215        2.280229